package defpackage;

import android.os.Build;
import com.google.android.gms.internal.ads.zzayq;
import com.google.android.gms.internal.ads.zzbad;
import com.google.android.gms.internal.ads.zzbas;
import com.google.android.gms.internal.ads.zzbcc;
import com.google.android.gms.internal.ads.zzbnf;
import com.google.android.gms.internal.ads.zzboh;
import com.google.android.gms.internal.ads.zzbvi;
import com.google.android.gms.internal.ads.zzbya;
import com.google.android.gms.internal.ads.zzbze;
import com.google.android.gms.internal.ads.zzbzu;
import com.google.android.gms.internal.ads.zzcab;
import com.google.android.gms.internal.ads.zzcco;
import com.google.android.gms.internal.ads.zzcew;
import com.google.android.gms.internal.ads.zzeei;

/* JADX INFO: loaded from: classes.dex */
public final class hd2 {
    public static final hd2 B = new hd2();
    public final zzcab A;
    public final m21 a;
    public final m21 b;
    public final cd2 c;
    public final zzcew d;
    public final fd2 e;
    public final zzayq f;
    public final zzbze g;
    public final k22 h;
    public final zzbad i;
    public final us j;
    public final di k;
    public final zzbcc l;
    public final t92 m;
    public final zzbvi n;
    public final zzbzu o;
    public final zzbnf p;
    public final wc0 q;
    public final bn1 r;
    public final ta1 s;
    public final b21 t;
    public final zzboh u;
    public final bm v;
    public final zzeei w;
    public final zzbya x;
    public final xh y;
    public final zzcco z;

    public hd2() {
        m21 m21Var = new m21();
        m21 m21Var2 = new m21();
        cd2 cd2Var = new cd2();
        zzcew zzcewVar = new zzcew();
        int i = Build.VERSION.SDK_INT;
        fd2 td2Var = i >= 30 ? new td2() : i >= 28 ? new rd2() : i >= 26 ? new md2() : i >= 24 ? new id2() : new fd2();
        zzayq zzayqVar = new zzayq();
        zzbze zzbzeVar = new zzbze();
        k22 k22Var = new k22();
        k22Var.a = false;
        k22Var.b = 1.0f;
        zzbad zzbadVar = new zzbad();
        us usVar = us.a;
        di diVar = new di(1);
        diVar.b = 0L;
        zzbcc zzbccVar = new zzbcc();
        t92 t92Var = new t92(1);
        zzbvi zzbviVar = new zzbvi();
        zzbzu zzbzuVar = new zzbzu();
        zzbnf zzbnfVar = new zzbnf();
        wc0 wc0Var = new wc0();
        wc0Var.j = null;
        wc0Var.g = false;
        wc0Var.i = null;
        wc0Var.k = null;
        wc0Var.h = null;
        bn1 bn1Var = new bn1();
        bn1Var.b = null;
        bn1Var.c = null;
        bn1Var.a = 0;
        bn1Var.d = new Object();
        ta1 ta1Var = new ta1(11);
        b21 b21Var = new b21(12);
        zzboh zzbohVar = new zzboh();
        bm bmVar = new bm(1);
        zzeei zzeeiVar = new zzeei();
        new zzbas();
        zzbya zzbyaVar = new zzbya();
        xh xhVar = new xh(2);
        zzcco zzccoVar = new zzcco();
        zzcab zzcabVar = new zzcab();
        this.a = m21Var;
        this.b = m21Var2;
        this.c = cd2Var;
        this.d = zzcewVar;
        this.e = td2Var;
        this.f = zzayqVar;
        this.g = zzbzeVar;
        this.h = k22Var;
        this.i = zzbadVar;
        this.j = usVar;
        this.k = diVar;
        this.l = zzbccVar;
        this.m = t92Var;
        this.n = zzbviVar;
        this.o = zzbzuVar;
        this.p = zzbnfVar;
        this.r = bn1Var;
        this.q = wc0Var;
        this.s = ta1Var;
        this.t = b21Var;
        this.u = zzbohVar;
        this.v = bmVar;
        this.w = zzeeiVar;
        this.x = zzbyaVar;
        this.y = xhVar;
        this.z = zzccoVar;
        this.A = zzcabVar;
    }
}
