package defpackage;

/* JADX INFO: loaded from: classes.dex */
public abstract class ww1 {
    public static final x5 a;
    public static final x5 b;
    public static final x5 c;
    public static final x5 d;

    static {
        new x5(0, "VISUAL_STATE_CALLBACK", "VISUAL_STATE_CALLBACK");
        new x5(0, "OFF_SCREEN_PRERASTER", "OFF_SCREEN_PRERASTER");
        new x5(3, "SAFE_BROWSING_ENABLE", "SAFE_BROWSING_ENABLE");
        new x5(1, "DISABLED_ACTION_MODE_MENU_ITEMS", "DISABLED_ACTION_MODE_MENU_ITEMS");
        new x5(4, "START_SAFE_BROWSING", "START_SAFE_BROWSING");
        new x5(4, "SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_WHITELIST");
        new x5(4, "SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_ALLOWLIST");
        new x5(4, "SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_WHITELIST");
        new x5(4, "SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_ALLOWLIST");
        new x5(4, "SAFE_BROWSING_PRIVACY_POLICY_URL", "SAFE_BROWSING_PRIVACY_POLICY_URL");
        new x5(1, "SERVICE_WORKER_BASIC_USAGE", "SERVICE_WORKER_BASIC_USAGE");
        new x5(1, "SERVICE_WORKER_CACHE_MODE", "SERVICE_WORKER_CACHE_MODE");
        new x5(1, "SERVICE_WORKER_CONTENT_ACCESS", "SERVICE_WORKER_CONTENT_ACCESS");
        new x5(1, "SERVICE_WORKER_FILE_ACCESS", "SERVICE_WORKER_FILE_ACCESS");
        new x5(1, "SERVICE_WORKER_BLOCK_NETWORK_LOADS", "SERVICE_WORKER_BLOCK_NETWORK_LOADS");
        new x5(1, "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST", "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST");
        new x5(0, "RECEIVE_WEB_RESOURCE_ERROR", "RECEIVE_WEB_RESOURCE_ERROR");
        new x5(0, "RECEIVE_HTTP_ERROR", "RECEIVE_HTTP_ERROR");
        new x5(1, "SHOULD_OVERRIDE_WITH_REDIRECTS", "SHOULD_OVERRIDE_WITH_REDIRECTS");
        new x5(4, "SAFE_BROWSING_HIT", "SAFE_BROWSING_HIT");
        new x5(1, "WEB_RESOURCE_REQUEST_IS_REDIRECT", "WEB_RESOURCE_REQUEST_IS_REDIRECT");
        new x5(0, "WEB_RESOURCE_ERROR_GET_DESCRIPTION", "WEB_RESOURCE_ERROR_GET_DESCRIPTION");
        new x5(0, "WEB_RESOURCE_ERROR_GET_CODE", "WEB_RESOURCE_ERROR_GET_CODE");
        new x5(4, "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY", "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY");
        new x5(4, "SAFE_BROWSING_RESPONSE_PROCEED", "SAFE_BROWSING_RESPONSE_PROCEED");
        new x5(4, "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL", "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL");
        new x5(0, "WEB_MESSAGE_PORT_POST_MESSAGE", "WEB_MESSAGE_PORT_POST_MESSAGE");
        new x5(0, "WEB_MESSAGE_PORT_CLOSE", "WEB_MESSAGE_PORT_CLOSE");
        a = new x5(2, "WEB_MESSAGE_ARRAY_BUFFER", "WEB_MESSAGE_ARRAY_BUFFER");
        new x5(0, "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK", "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK");
        new x5(0, "CREATE_WEB_MESSAGE_CHANNEL", "CREATE_WEB_MESSAGE_CHANNEL");
        new x5(0, "POST_WEB_MESSAGE", "POST_WEB_MESSAGE");
        new x5(0, "WEB_MESSAGE_CALLBACK_ON_MESSAGE", "WEB_MESSAGE_CALLBACK_ON_MESSAGE");
        new x5(3, "GET_WEB_VIEW_CLIENT", "GET_WEB_VIEW_CLIENT");
        new x5(3, "GET_WEB_CHROME_CLIENT", "GET_WEB_CHROME_CLIENT");
        new x5(6, "GET_WEB_VIEW_RENDERER", "GET_WEB_VIEW_RENDERER");
        new x5(6, "WEB_VIEW_RENDERER_TERMINATE", "WEB_VIEW_RENDERER_TERMINATE");
        new x5(5, "TRACING_CONTROLLER_BASIC_USAGE", "TRACING_CONTROLLER_BASIC_USAGE");
        new cj1();
        new cj1();
        new x5(6, "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE", "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE");
        new uw1();
        new x5(2, "PROXY_OVERRIDE", "PROXY_OVERRIDE:3");
        b = new x5(2, "MULTI_PROCESS", "MULTI_PROCESS_QUERY");
        new x5(6, "FORCE_DARK", "FORCE_DARK");
        new x5(2, "FORCE_DARK_STRATEGY", "FORCE_DARK_BEHAVIOR");
        c = new x5(2, "WEB_MESSAGE_LISTENER", "WEB_MESSAGE_LISTENER");
        new x5(2, "DOCUMENT_START_SCRIPT", "DOCUMENT_START_SCRIPT:1");
        new x5(2, "PROXY_OVERRIDE_REVERSE_BYPASS", "PROXY_OVERRIDE_REVERSE_BYPASS");
        new x5(2, "GET_VARIATIONS_HEADER", "GET_VARIATIONS_HEADER");
        new x5(2, "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY", "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY");
        new x5(2, "GET_COOKIE_INFO", "GET_COOKIE_INFO");
        new x5(2, "REQUESTED_WITH_HEADER_ALLOW_LIST", "REQUESTED_WITH_HEADER_ALLOW_LIST");
        new x5(2, "USER_AGENT_METADATA", "USER_AGENT_METADATA");
        new vw1(2, "MULTI_PROFILE", "MULTI_PROFILE");
        new x5(2, "ATTRIBUTION_REGISTRATION_BEHAVIOR", "ATTRIBUTION_BEHAVIOR");
        new x5(2, "WEBVIEW_MEDIA_INTEGRITY_API_STATUS", "WEBVIEW_INTEGRITY_API_STATUS");
        d = new x5(2, "MUTE_AUDIO", "MUTE_AUDIO");
    }
}
