package defpackage;

import android.view.ViewGroup;
import androidx.appcompat.widget.RtlSpacingHelper;
import java.util.HashMap;

/* JADX INFO: loaded from: classes.dex */
public final class zm {
    public int a;
    public String b;
    public final cn c;
    public final bn d;
    public final an e;
    public final dn f;
    public HashMap g;
    public ym h;

    public zm() {
        cn cnVar = new cn();
        cnVar.a = false;
        cnVar.b = 0;
        cnVar.c = 0;
        cnVar.d = 1.0f;
        cnVar.e = Float.NaN;
        this.c = cnVar;
        bn bnVar = new bn();
        bnVar.a = false;
        bnVar.b = -1;
        bnVar.c = 0;
        bnVar.d = null;
        bnVar.e = -1;
        bnVar.f = 0;
        bnVar.g = Float.NaN;
        bnVar.h = Float.NaN;
        bnVar.i = Float.NaN;
        bnVar.j = -1;
        bnVar.k = null;
        bnVar.l = -3;
        bnVar.m = -1;
        this.d = bnVar;
        an anVar = new an();
        anVar.a = false;
        anVar.b = false;
        anVar.e = -1;
        anVar.f = -1;
        anVar.g = -1.0f;
        anVar.h = true;
        anVar.i = -1;
        anVar.j = -1;
        anVar.k = -1;
        anVar.l = -1;
        anVar.m = -1;
        anVar.n = -1;
        anVar.o = -1;
        anVar.p = -1;
        anVar.q = -1;
        anVar.r = -1;
        anVar.s = -1;
        anVar.t = -1;
        anVar.u = -1;
        anVar.v = -1;
        anVar.w = -1;
        anVar.x = 0.5f;
        anVar.y = 0.5f;
        anVar.z = null;
        anVar.A = -1;
        anVar.B = 0;
        anVar.C = 0.0f;
        anVar.D = -1;
        anVar.E = -1;
        anVar.F = -1;
        anVar.G = 0;
        anVar.H = 0;
        anVar.I = 0;
        anVar.J = 0;
        anVar.K = 0;
        anVar.L = 0;
        anVar.M = 0;
        anVar.N = RtlSpacingHelper.UNDEFINED;
        anVar.O = RtlSpacingHelper.UNDEFINED;
        anVar.P = RtlSpacingHelper.UNDEFINED;
        anVar.Q = RtlSpacingHelper.UNDEFINED;
        anVar.R = RtlSpacingHelper.UNDEFINED;
        anVar.S = RtlSpacingHelper.UNDEFINED;
        anVar.T = RtlSpacingHelper.UNDEFINED;
        anVar.U = -1.0f;
        anVar.V = -1.0f;
        anVar.W = 0;
        anVar.X = 0;
        anVar.Y = 0;
        anVar.Z = 0;
        anVar.a0 = 0;
        anVar.b0 = 0;
        anVar.c0 = 0;
        anVar.d0 = 0;
        anVar.e0 = 1.0f;
        anVar.f0 = 1.0f;
        anVar.g0 = -1;
        anVar.h0 = 0;
        anVar.i0 = -1;
        anVar.m0 = false;
        anVar.n0 = false;
        anVar.o0 = true;
        anVar.p0 = 0;
        this.e = anVar;
        dn dnVar = new dn();
        dnVar.a = false;
        dnVar.b = 0.0f;
        dnVar.c = 0.0f;
        dnVar.d = 0.0f;
        dnVar.e = 1.0f;
        dnVar.f = 1.0f;
        dnVar.g = Float.NaN;
        dnVar.h = Float.NaN;
        dnVar.i = -1;
        dnVar.j = 0.0f;
        dnVar.k = 0.0f;
        dnVar.l = 0.0f;
        dnVar.m = false;
        dnVar.n = 0.0f;
        this.f = dnVar;
        this.g = new HashMap();
    }

    public static void a(zm zmVar, int i, nm nmVar) {
        zmVar.a = i;
        int i2 = nmVar.e;
        an anVar = zmVar.e;
        anVar.i = i2;
        anVar.j = nmVar.f;
        anVar.k = nmVar.g;
        anVar.l = nmVar.h;
        anVar.m = nmVar.i;
        anVar.n = nmVar.j;
        anVar.o = nmVar.k;
        anVar.p = nmVar.l;
        anVar.q = nmVar.m;
        anVar.r = nmVar.n;
        anVar.s = nmVar.o;
        anVar.t = nmVar.s;
        anVar.u = nmVar.t;
        anVar.v = nmVar.u;
        anVar.w = nmVar.v;
        anVar.x = nmVar.E;
        anVar.y = nmVar.F;
        anVar.z = nmVar.G;
        anVar.A = nmVar.p;
        anVar.B = nmVar.q;
        anVar.C = nmVar.r;
        anVar.D = nmVar.T;
        anVar.E = nmVar.U;
        anVar.F = nmVar.V;
        anVar.g = nmVar.c;
        anVar.e = nmVar.a;
        anVar.f = nmVar.b;
        anVar.c = ((ViewGroup.MarginLayoutParams) nmVar).width;
        anVar.d = ((ViewGroup.MarginLayoutParams) nmVar).height;
        anVar.G = ((ViewGroup.MarginLayoutParams) nmVar).leftMargin;
        anVar.H = ((ViewGroup.MarginLayoutParams) nmVar).rightMargin;
        anVar.I = ((ViewGroup.MarginLayoutParams) nmVar).topMargin;
        anVar.J = ((ViewGroup.MarginLayoutParams) nmVar).bottomMargin;
        anVar.M = nmVar.D;
        anVar.U = nmVar.I;
        anVar.V = nmVar.H;
        anVar.X = nmVar.K;
        anVar.W = nmVar.J;
        anVar.m0 = nmVar.W;
        anVar.n0 = nmVar.X;
        anVar.Y = nmVar.L;
        anVar.Z = nmVar.M;
        anVar.a0 = nmVar.P;
        anVar.b0 = nmVar.Q;
        anVar.c0 = nmVar.N;
        anVar.d0 = nmVar.O;
        anVar.e0 = nmVar.R;
        anVar.f0 = nmVar.S;
        anVar.l0 = nmVar.Y;
        anVar.O = nmVar.x;
        anVar.Q = nmVar.z;
        anVar.N = nmVar.w;
        anVar.P = nmVar.y;
        anVar.S = nmVar.A;
        anVar.R = nmVar.B;
        anVar.T = nmVar.C;
        anVar.p0 = nmVar.Z;
        anVar.K = nmVar.getMarginEnd();
        anVar.L = nmVar.getMarginStart();
    }

    public final void b(nm nmVar) {
        an anVar = this.e;
        nmVar.e = anVar.i;
        nmVar.f = anVar.j;
        nmVar.g = anVar.k;
        nmVar.h = anVar.l;
        nmVar.i = anVar.m;
        nmVar.j = anVar.n;
        nmVar.k = anVar.o;
        nmVar.l = anVar.p;
        nmVar.m = anVar.q;
        nmVar.n = anVar.r;
        nmVar.o = anVar.s;
        nmVar.s = anVar.t;
        nmVar.t = anVar.u;
        nmVar.u = anVar.v;
        nmVar.v = anVar.w;
        ((ViewGroup.MarginLayoutParams) nmVar).leftMargin = anVar.G;
        ((ViewGroup.MarginLayoutParams) nmVar).rightMargin = anVar.H;
        ((ViewGroup.MarginLayoutParams) nmVar).topMargin = anVar.I;
        ((ViewGroup.MarginLayoutParams) nmVar).bottomMargin = anVar.J;
        nmVar.A = anVar.S;
        nmVar.B = anVar.R;
        nmVar.x = anVar.O;
        nmVar.z = anVar.Q;
        nmVar.E = anVar.x;
        nmVar.F = anVar.y;
        nmVar.p = anVar.A;
        nmVar.q = anVar.B;
        nmVar.r = anVar.C;
        nmVar.G = anVar.z;
        nmVar.T = anVar.D;
        nmVar.U = anVar.E;
        nmVar.I = anVar.U;
        nmVar.H = anVar.V;
        nmVar.K = anVar.X;
        nmVar.J = anVar.W;
        nmVar.W = anVar.m0;
        nmVar.X = anVar.n0;
        nmVar.L = anVar.Y;
        nmVar.M = anVar.Z;
        nmVar.P = anVar.a0;
        nmVar.Q = anVar.b0;
        nmVar.N = anVar.c0;
        nmVar.O = anVar.d0;
        nmVar.R = anVar.e0;
        nmVar.S = anVar.f0;
        nmVar.V = anVar.F;
        nmVar.c = anVar.g;
        nmVar.a = anVar.e;
        nmVar.b = anVar.f;
        ((ViewGroup.MarginLayoutParams) nmVar).width = anVar.c;
        ((ViewGroup.MarginLayoutParams) nmVar).height = anVar.d;
        String str = anVar.l0;
        if (str != null) {
            nmVar.Y = str;
        }
        nmVar.Z = anVar.p0;
        nmVar.setMarginStart(anVar.L);
        nmVar.setMarginEnd(anVar.K);
        nmVar.a();
    }

    /* JADX INFO: renamed from: c, reason: merged with bridge method [inline-methods] */
    public final zm clone() {
        zm zmVar = new zm();
        zmVar.e.a(this.e);
        zmVar.d.a(this.d);
        cn cnVar = zmVar.c;
        cn cnVar2 = this.c;
        cnVar.a = cnVar2.a;
        cnVar.b = cnVar2.b;
        cnVar.d = cnVar2.d;
        cnVar.e = cnVar2.e;
        cnVar.c = cnVar2.c;
        zmVar.f.a(this.f);
        zmVar.a = this.a;
        zmVar.h = this.h;
        return zmVar;
    }
}
