package com.google.android.gms.internal.ads;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import defpackage.b0;
import defpackage.b92;
import defpackage.or1;
import defpackage.os;
import defpackage.rc2;
import defpackage.tb2;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/* JADX INFO: loaded from: classes.dex */
public final class zzbtz extends b0 {
    public static final Parcelable.Creator<zzbtz> CREATOR = new zzbua();
    public final long zzA;
    public final String zzB;
    public final float zzC;
    public final int zzD;
    public final int zzE;
    public final boolean zzF;
    public final String zzG;
    public final boolean zzH;
    public final String zzI;
    public final boolean zzJ;
    public final int zzK;
    public final Bundle zzL;
    public final String zzM;
    public final b92 zzN;
    public final boolean zzO;
    public final Bundle zzP;
    public final String zzQ;
    public final String zzR;
    public final String zzS;
    public final boolean zzT;
    public final List zzU;
    public final String zzV;
    public final List zzW;
    public final int zzX;
    public final boolean zzY;
    public final boolean zzZ;
    public final int zza;
    public final boolean zzaa;
    public final ArrayList zzab;
    public final String zzac;
    public final zzblh zzad;
    public final String zzae;
    public final Bundle zzaf;
    public final Bundle zzb;
    public final tb2 zzc;
    public final rc2 zzd;
    public final String zze;
    public final ApplicationInfo zzf;
    public final PackageInfo zzg;
    public final String zzh;
    public final String zzi;
    public final String zzj;
    public final or1 zzk;
    public final Bundle zzl;
    public final int zzm;
    public final List zzn;
    public final Bundle zzo;
    public final boolean zzp;
    public final int zzq;
    public final int zzr;
    public final float zzs;
    public final String zzt;
    public final long zzu;
    public final String zzv;
    public final List zzw;
    public final String zzx;
    public final zzbes zzy;
    public final List zzz;

    public zzbtz(int i, Bundle bundle, tb2 tb2Var, rc2 rc2Var, String str, ApplicationInfo applicationInfo, PackageInfo packageInfo, String str2, String str3, String str4, or1 or1Var, Bundle bundle2, int i2, List list, Bundle bundle3, boolean z, int i3, int i4, float f, String str5, long j, String str6, List list2, String str7, zzbes zzbesVar, List list3, long j2, String str8, float f2, boolean z2, int i5, int i6, boolean z3, String str9, String str10, boolean z4, int i7, Bundle bundle4, String str11, b92 b92Var, boolean z5, Bundle bundle5, String str12, String str13, String str14, boolean z6, List list4, String str15, List list5, int i8, boolean z7, boolean z8, boolean z9, ArrayList arrayList, String str16, zzblh zzblhVar, String str17, Bundle bundle6) {
        this.zza = i;
        this.zzb = bundle;
        this.zzc = tb2Var;
        this.zzd = rc2Var;
        this.zze = str;
        this.zzf = applicationInfo;
        this.zzg = packageInfo;
        this.zzh = str2;
        this.zzi = str3;
        this.zzj = str4;
        this.zzk = or1Var;
        this.zzl = bundle2;
        this.zzm = i2;
        this.zzn = list;
        this.zzz = list3 == null ? Collections.EMPTY_LIST : Collections.unmodifiableList(list3);
        this.zzo = bundle3;
        this.zzp = z;
        this.zzq = i3;
        this.zzr = i4;
        this.zzs = f;
        this.zzt = str5;
        this.zzu = j;
        this.zzv = str6;
        this.zzw = list2 == null ? Collections.EMPTY_LIST : Collections.unmodifiableList(list2);
        this.zzx = str7;
        this.zzy = zzbesVar;
        this.zzA = j2;
        this.zzB = str8;
        this.zzC = f2;
        this.zzH = z2;
        this.zzD = i5;
        this.zzE = i6;
        this.zzF = z3;
        this.zzG = str9;
        this.zzI = str10;
        this.zzJ = z4;
        this.zzK = i7;
        this.zzL = bundle4;
        this.zzM = str11;
        this.zzN = b92Var;
        this.zzO = z5;
        this.zzP = bundle5;
        this.zzQ = str12;
        this.zzR = str13;
        this.zzS = str14;
        this.zzT = z6;
        this.zzU = list4;
        this.zzV = str15;
        this.zzW = list5;
        this.zzX = i8;
        this.zzY = z7;
        this.zzZ = z8;
        this.zzaa = z9;
        this.zzab = arrayList;
        this.zzac = str16;
        this.zzad = zzblhVar;
        this.zzae = str17;
        this.zzaf = bundle6;
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i) {
        int i2 = this.zza;
        int iE = os.E(20293, parcel);
        os.G(parcel, 1, 4);
        parcel.writeInt(i2);
        os.v(parcel, 2, this.zzb);
        os.y(parcel, 3, this.zzc, i);
        os.y(parcel, 4, this.zzd, i);
        os.z(parcel, 5, this.zze);
        os.y(parcel, 6, this.zzf, i);
        os.y(parcel, 7, this.zzg, i);
        os.z(parcel, 8, this.zzh);
        os.z(parcel, 9, this.zzi);
        os.z(parcel, 10, this.zzj);
        os.y(parcel, 11, this.zzk, i);
        os.v(parcel, 12, this.zzl);
        int i3 = this.zzm;
        os.G(parcel, 13, 4);
        parcel.writeInt(i3);
        os.B(parcel, 14, this.zzn);
        os.v(parcel, 15, this.zzo);
        boolean z = this.zzp;
        os.G(parcel, 16, 4);
        parcel.writeInt(z ? 1 : 0);
        int i4 = this.zzq;
        os.G(parcel, 18, 4);
        parcel.writeInt(i4);
        int i5 = this.zzr;
        os.G(parcel, 19, 4);
        parcel.writeInt(i5);
        float f = this.zzs;
        os.G(parcel, 20, 4);
        parcel.writeFloat(f);
        os.z(parcel, 21, this.zzt);
        long j = this.zzu;
        os.G(parcel, 25, 8);
        parcel.writeLong(j);
        os.z(parcel, 26, this.zzv);
        os.B(parcel, 27, this.zzw);
        os.z(parcel, 28, this.zzx);
        os.y(parcel, 29, this.zzy, i);
        os.B(parcel, 30, this.zzz);
        long j2 = this.zzA;
        os.G(parcel, 31, 8);
        parcel.writeLong(j2);
        os.z(parcel, 33, this.zzB);
        float f2 = this.zzC;
        os.G(parcel, 34, 4);
        parcel.writeFloat(f2);
        int i6 = this.zzD;
        os.G(parcel, 35, 4);
        parcel.writeInt(i6);
        int i7 = this.zzE;
        os.G(parcel, 36, 4);
        parcel.writeInt(i7);
        boolean z2 = this.zzF;
        os.G(parcel, 37, 4);
        parcel.writeInt(z2 ? 1 : 0);
        os.z(parcel, 39, this.zzG);
        boolean z3 = this.zzH;
        os.G(parcel, 40, 4);
        parcel.writeInt(z3 ? 1 : 0);
        os.z(parcel, 41, this.zzI);
        boolean z4 = this.zzJ;
        os.G(parcel, 42, 4);
        parcel.writeInt(z4 ? 1 : 0);
        int i8 = this.zzK;
        os.G(parcel, 43, 4);
        parcel.writeInt(i8);
        os.v(parcel, 44, this.zzL);
        os.z(parcel, 45, this.zzM);
        os.y(parcel, 46, this.zzN, i);
        boolean z5 = this.zzO;
        os.G(parcel, 47, 4);
        parcel.writeInt(z5 ? 1 : 0);
        os.v(parcel, 48, this.zzP);
        os.z(parcel, 49, this.zzQ);
        os.z(parcel, 50, this.zzR);
        os.z(parcel, 51, this.zzS);
        boolean z6 = this.zzT;
        os.G(parcel, 52, 4);
        parcel.writeInt(z6 ? 1 : 0);
        List list = this.zzU;
        if (list != null) {
            int iE2 = os.E(53, parcel);
            int size = list.size();
            parcel.writeInt(size);
            for (int i9 = 0; i9 < size; i9++) {
                parcel.writeInt(((Integer) list.get(i9)).intValue());
            }
            os.F(iE2, parcel);
        }
        os.z(parcel, 54, this.zzV);
        os.B(parcel, 55, this.zzW);
        int i10 = this.zzX;
        os.G(parcel, 56, 4);
        parcel.writeInt(i10);
        boolean z7 = this.zzY;
        os.G(parcel, 57, 4);
        parcel.writeInt(z7 ? 1 : 0);
        boolean z8 = this.zzZ;
        os.G(parcel, 58, 4);
        parcel.writeInt(z8 ? 1 : 0);
        boolean z9 = this.zzaa;
        os.G(parcel, 59, 4);
        parcel.writeInt(z9 ? 1 : 0);
        os.B(parcel, 60, this.zzab);
        os.z(parcel, 61, this.zzac);
        os.y(parcel, 63, this.zzad, i);
        os.z(parcel, 64, this.zzae);
        os.v(parcel, 65, this.zzaf);
        os.F(iE, parcel);
    }
}
